let score = "33";
console.log(typeof score);
let value = Number(score);
console.log(typeof value);
// "33" => 33;
//"33abc" => NaN;
// true => 1;
// false=> 0;
let bool = " arpit ";
let ans = Boolean(bool);
console.log(ans);
// 1 => true;
// 0 => false;
//"" => false;
// "  " => true;
//"arpit" => true;